### ISSUE TITLE
Eskalation

### ISSUE THREAD

**Issue by aresage29** [Y01Builder/Schiffe_ERMORDEN#1]
Das Programm ist laut normalen Vorgaben zu normal. Ich fordere mehr Eskalation. So minimum ein Webserver hintendran

**Comment by Y01Builder** [comment]
Features needed:
- Websupport (SQL Backend)
- Charakter erstellung
- Schwierigkeitssettings
- KI Training
- ASCII Animationen
- endoplasmatisches Ritikulum
- Grundfunktionen des Spiels
- Tests
- Sounddesign
- WorldWideLeaderbord
- Ränge & Ligen
- Lazy Town Reference in der Doku
- Dokumentation

**Comment by Y01Builder** [comment]
Doc and  ASCII implemented, rest out of budget. Budget being my f*cking nerves.
