### ISSUE TITLE
Possible rename

### ISSUE THREAD

**Issue by aresage29** [Y01Builder/Schiffe_ERMORDEN#10]
https://github.com/Y01Builder/Schiffe_ERMORDEN/blob/0ebac8452f40442f8a3f042c5901b459f7ec0b1b/DTO/bot_player.py#L115

Ich weiß nicht ob der Widemann das so feiert in der abgabe. Auch wenn ich es unterstütze

**Comment by pr0ga** [comment]
Done. Heißt jetzt __statistical_analysis
