### ISSUE TITLE
WTF?????????????????

### ISSUE THREAD

**Issue by aresage29** [Y01Builder/Schiffe_ERMORDEN#11]
https://github.com/Y01Builder/Schiffe_ERMORDEN/blob/0ebac8452f40442f8a3f042c5901b459f7ec0b1b/DTO/bot_player.py#L110

Erklär bitte was das macht, ich hab Fragen. Und btw: refactor weil pylint dumm ist

**Comment by Y01Builder** [comment]
würde ihm vielleicht nochmal auf Whatsapp schreiben. weiß nicht wie oft er hier rein schaut

**Comment by aresage29** [comment]
Ist schon geklärt, habe nur vergessen den issue zuzumachen
