### ISSUE TITLE
Hardcoding?

### ISSUE THREAD

**Issue by aresage29** [Y01Builder/Schiffe_ERMORDEN#12]
https://github.com/Y01Builder/Schiffe_ERMORDEN/blob/a4ceb64d51ba284d88dad94195bf2fdb5049a5a2/DTO/map.py#L21

Nur als Vorschlag: Aber die Anzahl evtl. nicht hardcoden, sondern beim Plazieren anpassen?

**Comment by Y01Builder** [comment]
Zack feddisch. Felder werden jetzt hochgezählt, wenn ein Schifftile als solches gesetzt wird.
