### ISSUE TITLE
UX

### ISSUE THREAD

**Issue by aresage29** [Y01Builder/Schiffe_ERMORDEN#13]
https://github.com/Y01Builder/Schiffe_ERMORDEN/blob/a4ceb64d51ba284d88dad94195bf2fdb5049a5a2/DTO/player.py#L168

Evtl. auch kleinbuchstaben zulassen? Also abfragen aber nicht hinschreiben. Das ist deutlich angenehmer für den Nutzer

**Comment by aresage29** [comment]
![image](https://user-images.githubusercontent.com/63734958/235500581-99868024-e3bd-47b7-96a6-ee4f2a2002b7.png)

https://github.com/Y01Builder/Schiffe_ERMORDEN/blob/a4ceb64d51ba284d88dad94195bf2fdb5049a5a2/DTO/player.py#L94

Evtl. an den Anfang der Funktion als "Player Ready?" verschieben? Spart einem diesen hässlichen endoutput

**Comment by Y01Builder** [comment]
wurde in game.py verschoben um diesen M*ist zu verhindern.

**Comment by aresage29** [comment]
- [x] Pause nach Ergebnis, sonst nicht lesbar
- [x] clear zu beginn
- [x] clear zum ende

**Comment by Y01Builder** [comment]
noch ein paar clears mehr eingefügt für ultimate clean. Da hält nichtmal Meister Propper mit!
