### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Y01Builder** [Y01Builder/Schiffe_ERMORDEN#3]
Die testigen Unittests die testen.

**Comment by aresage29** [comment]
- [x] Rename folder containing tests to "test"
- [x] Add "\_\_init__.py" to tests for easy run 

=> so all tests can be run with "python -m unittest discover -v"and coverage with "python -m coverage run -m unittest"

**Comment by aresage29** [comment]
Überarbeitung der Tests nötig. Siehe Bild

![image](https://user-images.githubusercontent.com/63734958/235512735-a4d12ca5-9fe7-47b0-bd59-a1bf6ff08214.png)
