### ISSUE TITLE
Dokumentation

### ISSUE THREAD

**Issue by Y01Builder** [Y01Builder/Schiffe_ERMORDEN#5]
für masochistisch veranlagte.

**Comment by aresage29** [comment]
- [x] V-Modell grafisch
- [x] Aktivitätsdiagramme
- [x] Architekturbeschreibung
- [x] UI/UX erklären
- [x] computergegner + Funktion erklären
- [x] Speicherformat erklären
- [x] Spielablauf aufzeigen
- [x] Unittests
- [x] Testabdeckung
- [x] Umgang mit Fehlern

**Comment by aresage29** [comment]
- [x] add rules how to start unittest and coverage
